# Generated by Django 3.2.9 on 2021-11-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_renekton', '0004_post_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
